Implementing Delete Account Function
Issue: when deleting account in auth:
com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException: This operation is sensitive and requires recent authentication. Log in again before retrying this request.